apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default  # Change if using a different namespace
type: Opaque
data:
  postgres-password: MTIz  # Base64-encoded '123'; use `echo -n 'your-password' | base64`
  postgres-user: cG9zdGdyZXM=  # Base64 'postgres'
  postgres-db: cHJvZHVjdA==  # Base64 'product'

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  spring-datasource-url: amRiYzpwb3N0Z3Jlc3FsOi8vc3ByaW5nLWFwcC1kYjo1NDMyL3Byb2R1Y3Q=  # Base64 'jdbc:postgresql://spring-app-db:5432/product'
  spring-datasource-username: cG9zdGdyZXM=  # Base64 'postgres'
  spring-datasource-password: MTIz  # Base64 '123'
